// Selection summaries are original, brief guidance; full features are a later milestone.
export const speciesDetails = {
  Dragonborn: {description: 'A draconic hero with scales and a powerful ancestral connection. Imagine the color and presence you bring to the party.'},
  Dwarf: {description: 'A sturdy, long-lived adventurer. Your story might begin among mountain halls, busy cities, or somewhere entirely unexpected.'},
  Elf: {description: 'A long-lived person with fey ancestry. Keen senses and a trance in place of sleep; the forests, courts or wandering roads you came from are yours to decide.'},
  'Dark Elf': {description: 'A Drow elf, with a lineage often associated with the Underdark. Your upbringing, loyalties, and personality are yours to define.', note: 'Dark Elf is the Drow lineage of the 2024 Elf. It appears separately here for easy selection.', baseSpecies: 'Elf', lineage: 'Drow'},
  Gnome: {description: 'A small adventurer with a spark of magic. Picture a curious explorer, thoughtful scholar, or a hero who surprises everyone.'},
  Goblin: {description: 'A small goblinoid with a talent for slipping out of danger. A goblin can pursue any calling, including a healer or inventor.', note: 'Uses the Monsters of the Multiverse Goblin as an older species option. Ability bonuses come only from your 2024 background.', source: 'Monsters of the Multiverse (2022)'},
  Goliath: {description: 'A towering adventurer with giant ancestry. Decide how that larger-than-life heritage fits a very personal story.'},
  'Half-Elf': {description: 'A person with human and elven ancestry. Explore the connections, communities, and traditions that shaped your own identity.', note: 'Uses the 2014 Half-Elf as an older species option. Ability bonuses come only from your 2024 background.', source: 'Player’s Handbook (2014)'},
  Halfling: {description: 'A small hero with room for great courage. You might leave a familiar home behind or already know every road on the map.'},
  Human: {description: 'An adaptable adventurer from any walk of life. Decide what ambition, curiosity, or connection draws you into this story.'},
  Orc: {description: 'A resilient adventurer with a powerful presence. Your community and personal choices define the kind of hero you become.'},
  Tiefling: {description: 'A person with a supernatural fiendish legacy. Choose how your appearance expresses that heritage and how you make it your own.'},
};
export const classDetails = {
  Artificer: {description: 'Blend magical study with invention. Imagine solving problems with enchanted tools, crafted objects, and practical ingenuity.', ability: 'Intelligence'},
  Barbarian: {description: 'Meet danger head-on with fierce strength and endurance. A good fit if you imagine a physical protector or relentless warrior.', ability: 'Strength'},
  Bard: {description: 'Use performance and magic to inspire companions and influence a scene. Your instrument might be music, storytelling, or a commanding voice.', ability: 'Charisma'},
  Cleric: {description: 'Channel divine magic to help allies and confront threats. Decide what faith or sacred purpose guides your character.', ability: 'Wisdom'},
  Druid: {description: 'Draw magic from the natural world. Explore a connection to animals, landscapes, seasons, or the balance between them.', ability: 'Wisdom'},
  Fighter: {description: 'Rely on weapon training and adaptable combat skills. Picture your preferred weapons and how you learned to use them.', ability: 'Strength or Dexterity'},
  Monk: {description: 'Turn disciplined movement into a fighting style. Imagine a mobile adventurer who develops body and mind together.', ability: 'Dexterity and Wisdom'},
  Paladin: {description: 'Combine martial training with a sacred commitment. Decide which ideals you would defend when keeping them becomes difficult.', ability: 'Strength and Charisma'},
  Ranger: {description: 'Mix tracking, weapons, and nature magic. You might guide a group through dangerous country or pursue a threat across it.', ability: 'Dexterity and Wisdom'},
  Rogue: {description: 'Use precision, clever timing, and practiced skills. Consider whether you are an investigator, scout, thief, or something else entirely.', ability: 'Dexterity'},
  Sorcerer: {description: 'Wield magic that comes from within. Imagine how that power first appeared and how your character feels about it.', ability: 'Charisma'},
  Warlock: {description: 'Explore magic connected to a powerful patron. Think about what drew you toward that relationship and what you hope to gain.', ability: 'Charisma'},
  Wizard: {description: 'Learn magic through careful study and experimentation. Decide what questions or discoveries keep you searching for more knowledge.', ability: 'Intelligence'},
};
export const backgroundDescriptions = {
  Acolyte: 'Temple service shaped your early life.',
  Artisan: 'You learned a craft through practical work.',
  Charlatan: 'You made a living selling convincing illusions.',
  Criminal: 'You learned to operate outside the law.',
  Entertainer: 'You practiced winning an audience’s attention.',
  Farmer: 'Land and livestock taught you daily resilience.',
  Guard: 'You learned to notice trouble while standing watch.',
  Guide: 'You helped others find their way through wilderness.',
  Hermit: 'Time apart gave you space for reflection.',
  Merchant: 'Trade taught you to recognize opportunity.',
  Noble: 'Status brought privilege, responsibility, and expectations.',
  Sage: 'You pursued answers among books and scholars.',
  Sailor: 'Life aboard ships taught you adaptability.',
  Scribe: 'You worked carefully with records and written words.',
  Soldier: 'Military service taught you discipline under pressure.',
  Wayfarer: 'You learned to survive with few reliable resources.',
};
export const abilityDescriptions = {
  Strength: 'Physical force: lifting, climbing, and powerful blows.',
  Dexterity: 'Agility, balance, stealth, and precise movement.',
  Constitution: 'Endurance and resistance to physical strain.',
  Intelligence: 'Reasoning, recall, and learned knowledge.',
  Wisdom: 'Awareness, intuition, and reading your surroundings.',
  Charisma: 'Presence, expression, and influencing others.',
};
