import {freshStoryGame} from './storyRules';
import {combatBasics} from './combatRules';
// Written locally so combat can be tested instantly without story generation.
// Stat blocks are tuned for a level-1 hero and scale with level; groups share one HP pool and every standing member attacks.
const saves=(Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma)=>({Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma});
export const hostileFoes=[
 {key:'bandit',foe:'Bandit Cutthroat',species:'Human',type:'Slashing',hp:16,ac:12,atk:3,die:6,bonus:1,saves:saves(0,1,1,0,0,0),appearance:'A lean human bandit in a patched leather jerkin and a mud-stained hood, a notched scimitar in one hand and a knife in the other. A scarf covers the lower face; a crude tattoo of a crow marks one wrist.',place:'Overgrown Roadside',scene:'A rutted forest road narrowed by brambles, where a toppled cart blocks the way.'},
 {key:'wolf',foe:'Starving Dire Wolf',species:'Dire wolf',type:'Piercing',hp:18,ac:13,atk:4,die:6,bonus:2,saves:saves(2,2,2,-4,1,-2),appearance:'A huge grey-black wolf, ribs showing through matted fur, yellow eyes and a torn left ear. Its muzzle is scarred and its hackles stand high.',place:'Frozen Pine Hollow',scene:'A snow-dusted hollow ringed by dark pines, with fresh tracks circling a fallen log.'},
 {key:'goblin',foe:'Goblin Raider',species:'Goblin',type:'Slashing',group:{size:3,memberHP:7,plural:'goblin raiders',count:'Three'},ac:13,atk:3,die:4,bonus:1,saves:saves(-1,2,0,0,-1,-1),appearance:'A wiry green-grey goblin with oversized ears, a jagged grin and a helmet made from a dented cooking pot. It carries a chipped short blade and a rope belt hung with stolen trinkets.',place:'Raided Waystation',scene:'A burned-out waystation with a smashed well cover and scattered supply crates.'},
 {key:'skeleton',foe:'Restless Skeleton',species:'Undead skeleton',type:'Piercing',hp:16,ac:13,atk:4,die:6,bonus:2,saves:saves(0,2,2,-2,-1,-3),appearance:'A yellowed human skeleton in rusted mail scraps, a cracked round shield strapped to one arm and a corroded shortsword in hand. Faint blue light flickers in its eye sockets.',place:'Collapsed Barrow',scene:'A broken burial mound on a hillside, its stone door split open to the night air.'},
 {key:'boar',foe:'Enraged Boar',species:'Boar',type:'Slashing',hp:15,ac:11,atk:3,die:6,bonus:1,saves:saves(1,0,1,-4,-2,-3),appearance:'A massive bristle-backed boar with curved, chipped tusks, a torn ear and a broken arrow shaft lodged in its flank. It paws furrows into the earth.',place:'Trampled Orchard',scene:'An abandoned orchard of gnarled apple trees, the ground torn up by heavy hooves.'},
 {key:'spider',foe:'Giant Cave Spider',species:'Giant spider',type:'Poison',hp:14,ac:13,atk:4,die:6,bonus:1,saves:saves(0,3,1,-4,1,-3),appearance:'A spider the size of a large dog, with glossy black legs banded in rust red, eight clustered amber eyes and dripping fangs. Web strands trail from its abdomen.',place:'Web-Choked Ravine',scene:'A narrow rocky ravine strung with thick grey webs that catch the light.'},
 {key:'zombies',foe:'Rotting Zombie',species:'Undead zombie',type:'Bludgeoning',group:{size:2,memberHP:11,plural:'rotting zombies',count:'Two'},ac:8,atk:3,die:6,bonus:1,saves:saves(1,-2,3,-4,-2,-3),appearance:'A shambling corpse in the rags of a farmhand’s smock, grey skin split and sagging, one eye clouded white. Its jaw hangs loose and dirt cakes its reaching hands.',place:'Flooded Graveyard',scene:'A sunken village graveyard where toppled headstones lean out of black standing water.'},
 {key:'orc',foe:'Orc Marauder',species:'Orc',type:'Slashing',hp:20,ac:13,atk:5,die:8,bonus:3,saves:saves(3,1,3,-2,0,0),appearance:'A broad-shouldered grey-green orc with a shaved scalp, jutting lower tusks and a scarred lip, wearing scavenged ring mail and a wolf-pelt mantle. It swings a heavy notched greataxe.',place:'Burning Farmstead',scene:'A farmhouse yard lit by a smouldering barn, with a broken fence and scattered livestock pens.'},
 {key:'wolves',foe:'Grey Wolf',species:'Wolf',type:'Piercing',group:{size:2,memberHP:9,plural:'grey wolves',count:'Two'},ac:13,atk:4,die:4,bonus:2,saves:saves(1,2,1,-4,1,-2),appearance:'A lean grey timber wolf with a pale chest, amber eyes and a ridge of raised fur along its back. Its lips pull back from long yellowed fangs.',place:'Moonlit Clearing',scene:'A frost-silvered clearing in an old forest, ringed by leaning birches.'},
];
// Per level above 1: tougher HP pool, and steadily better attacks and armor.
export function foeStatsFor(f,level=1){
 const up=Math.max(0,level-1),memberHP=Math.round((f.group?f.group.memberHP:f.hp)*(1+0.8*up));
 return {maximum:memberHP*(f.group?.size??1),ac:f.ac+Math.floor(up/4),attackBonus:f.atk+Math.floor(up/2),die:f.die,count:1+Math.floor(up/5),bonus:f.bonus+Math.floor(up/2),type:f.type,saves:f.saves,...(f.group?{group:{size:f.group.size,memberHP,plural:f.group.plural}}:{})};
}
export function hostileEncounterGame(hero,base,random=Math.random){
 // Fragile low-level heroes (under 10 HP, such as a new wizard) meet a single foe, never a pack or the orc.
 const hp=combatBasics(hero)?.hp,pool=Number.isFinite(hp)&&hp<10&&(hero.level??1)<=2?hostileFoes.filter(f=>!f.group&&f.key!=='orc'):hostileFoes;
 const f=pool[Math.floor(random()*pool.length)],stats=foeStatsFor(f,hero.level??1),many=f.group?f.group.count+' '+f.group.plural.replace(/^./,c=>c.toUpperCase()):'A '+f.foe;
 const story={id:'hostile-encounter-'+f.key,introId:'hostile',status:'active',title:'Random hostile encounter: '+(f.group?f.group.count+' '+f.group.plural:f.foe),
  premise:'A combat test: '+(f.group?f.group.count.toLowerCase()+' '+f.group.plural:'a '+f.foe)+(f.group?' ambush ':' ambushes ')+hero.name+' at the '+f.place+' while travelling with a small caravan.',
  opening:many+' burst from cover at the '+f.place+' and '+(f.group?'close in':'lunge for you')+'. '+(f.group?'They haven\'t':'It hasn\'t')+' closed the gap yet — you have the first move. Describe your attack, spell or other action.',
  objective:'Defeat or drive off the '+(f.group?f.group.plural:f.foe)+'.',resolution:'Every attacker is defeated, or the player escapes and regroups at the caravan camp.',secret:'There is no hidden twist; this is a straightforward combat test encounter.',
  foe:f.foe,foeSpecies:f.species,foeAppearance:f.appearance,foeDamageType:f.type,foeStats:stats,
  locations:{inn:{name:'Caravan Camp',description:'A ring of covered wagons around a smoky campfire, a short walk back along the road.'},bridge:{name:f.place,description:f.scene},tower:{name:'Lookout Rock',description:'A lichen-covered boulder above the road with a clear view of the surrounding country.'}},
  npcs:{keeper:{name:'Captain Oona Brask',species:'Dwarf',role:'Caravan guard captain who hired the player as an escort.',motive:'Get the wagons through safely and pay out only for honest work.',appearance:'A stocky middle-aged dwarf woman with a braided copper beard ring, weathered tan skin, a dented steel cap and a green caravan tabard over chain mail. A ledger hangs from her belt.',personality:'Blunt, dry-humoured and practical; speaks in short clipped sentences.'},
   mara:{name:'Tobin Reed',species:'Halfling',role:'Young caravan scout and cook.',motive:'Prove himself useful to the captain without getting anyone hurt.',appearance:'A slight young halfling man with unruly sandy hair, freckles, a patched brown cloak, a sling at his hip and a wooden spoon tucked behind one ear.',personality:'Eager, talkative and a little nervous; jokes when frightened.'}}};
 const game=freshStoryGame(hero,story,base);
 return {...game,stage:'combat',enemyHP:stats.maximum,openingAttackAvailable:true,map:{...game.map,visited:['inn','bridge']},log:[story.opening]};
}
