const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const base=fs.readFileSync('characterRules.js','utf8')+'\n'+fs.readFileSync('skillRules.js','utf8');
const s=vm.runInNewContext(base.replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')+'\n({skillCheckBonus,validSkillTraining})');
const hero={class:'Rogue',level:7,background:'Criminal',scores:{Strength:8,Dexterity:16,Constitution:14,Intelligence:12,Wisdom:10,Charisma:13}};
const game={skillTraining:{skills:['Acrobatics','Insight'],expertise:['Stealth']}};
assert.ok(s.validSkillTraining(game.skillTraining,hero));
assert.equal(s.skillCheckBonus(hero,game,'Dexterity','Stealth').total,9);
assert.equal(s.skillCheckBonus(hero,game,'Dexterity','Stealth').reliable,true);
assert.equal(s.skillCheckBonus(hero,game,'Dexterity','Acrobatics').total,6);
assert.equal(s.skillCheckBonus(hero,game,'Strength','Athletics').total,-1);
assert.equal(s.skillCheckBonus({...hero,class:'Bard',level:5},{},'Strength','Athletics').total,0);
assert.equal(s.skillCheckBonus({...hero,class:'Bard',level:5},{},'Strength',null).total,-1);
assert.equal(s.validSkillTraining({skills:['Stealth'],expertise:[]},hero),false,'no duplicate background choice');
assert.equal(s.validSkillTraining({skills:[],expertise:['Arcana']},hero),false);
const r=require('./verify-dm-integration.cjs');hero.equipment=r.equipmentFor(hero);
const scene={...r.newAdventure(hero),...game},hp={current:20,temp:0};
const plan={skill:'Stealth',ability:'Dexterity',dc:18,mode:'normal',reason:'Sneak quietly',success:'You pass quietly.',failure:'The floor creaks.',damageCount:0,damageDie:6,damageOn:'none'};
const result=r.commitDmTurn(hero,scene,hp,{type:'ai-check',check:plan},{question:'I sneak across the room.',narration:'You try to move quietly.'},()=>0);
assert.equal(result.error,undefined);assert.ok(result.game.log[0].includes('= 19 vs DC 18. Success'));assert.ok(result.game.log[0].includes('Reliable Talent'));assert.ok(r.validAdventure(r.adventureSnapshot(hero,result.game,hp,true),hero));
assert.ok(r.commitDmTurn(hero,scene,hp,{type:'ai-check',check:plan},{question:'I attack the keeper.',narration:'You try.'},()=>0).error);
const weak={...hero,class:'Wizard',level:1,background:'Sage',scores:{...hero.scores,Strength:1}};weak.equipment=r.equipmentFor(weak);
const impossible=r.commitDmTurn(weak,r.newAdventure(weak),{current:6,temp:0},{type:'ai-check',check:{...plan,skill:'Athletics',ability:'Strength',dc:30}},{question:'I lift the boulder.',narration:'You try.'},()=>0.99);assert.ok(impossible.game.log[0].includes('Failure'),'natural 20 does not automatically succeed on checks');
console.log('Passed: proficiency, Expertise, half proficiency, Reliable Talent, negative modifiers, no auto-success, skill choices and save validation, and attack/check isolation.');
