const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let raw=null,fail=false;
const AsyncStorage={getItem:async()=>raw,setItem:async(k,v)=>{if(fail)throw Error('Disk failure');raw=v;}};
const source='const catalog='+fs.readFileSync('spellCatalog.json','utf8')+';const progression='+fs.readFileSync('spellProgression.json','utf8')+';\n'+['subclassOptions.js','campaignRules.js','mapRules.js','journalRules.js','spellOptions.js','equipmentRules.js','characterRules.js','combatRules.js','weaponRules.js','healthRules.js','spellRules.js','classActions.js','dungeonRules.js','deathRules.js','npcRules.js','relationshipRules.js','hostileEncounter.js','encounterRules.js','inventoryRules.js','adventureRules.js','skillRules.js','storyRules.js','followerRules.js','adventureStorage.js','dmCommands.js','dmContext.js'].map(f=>fs.readFileSync(f,'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')).join('\n');
const open=()=>vm.runInNewContext(source+'\n({inspectSpellCast,knownSpells,dungeonChoices,dungeonState,dmCommand,commitDmTurn,dmContext,earnedGold,interactionOptions,dmChoices,newAdventure,adventureStep,journalForGame,addJournalNote,validJournal,adventureSnapshot,saveAdventure,loadAdventure,equipmentFor})',{AsyncStorage});
(async()=>{
 const r=open(),hero={name:'Dungeon tester',class:'Fighter',level:1,scores:{Strength:16,Dexterity:14,Constitution:14,Intelligence:12,Wisdom:12,Charisma:10}};hero.equipment=r.equipmentFor(hero);
 let game=r.newAdventure(hero),health=null;
 const act=action=>{const result=r.adventureStep(game,health,hero,action,()=>0.99);assert.equal(result.error,undefined,action);game=result.game;health=result.health;};
 assert.ok(r.adventureStep(game,health,hero,'dungeon:enter').error);
 act('listen');act({type:'travel',destination:'tower'});act('inspect-tower');act({type:'travel',destination:'bridge'});act('call-wisp');act('claim-reward');act('dungeon:enter');
 assert.equal(game.stage,'dungeon');assert.ok(game.map.visited.includes('dungeon'));
 act('dungeon:move:1');act('dungeon:move:2');assert.ok(r.adventureStep(game,health,hero,'dungeon:move:4').error);act('dungeon:fight');act('attack:Greatsword');assert.equal(game.stage,'dungeon');assert.ok(game.dungeon.cleared.includes(2));
 act('dungeon:move:4');act('dungeon:search');act('dungeon:move:3');act('dungeon:disarm');assert.ok(game.dungeon.trapResolved);act('dungeon:move:4');act('dungeon:move:5');assert.ok(r.adventureStep(game,health,hero,'dungeon:move:6').error);act('dungeon:dawn');act('dungeon:basin');assert.ok(r.adventureStep(game,health,hero,'dungeon:basin').error);
 await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);const restored=await open().loadAdventure(hero);game=restored.game;health=restored.health;assert.ok(game.dungeon.sealOpen);
 act('dungeon:move:6');act('dungeon:fight');act('attack:Greatsword');assert.equal(game.stage,'dungeon');act('dungeon:move:7');act('dungeon:claim');assert.equal(r.earnedGold(game),95);assert.ok(r.adventureStep(game,health,hero,'dungeon:claim').error);
 act('dungeon:leave');assert.equal(game.stage,'bridge');assert.equal(game.enemyHP,0);act('dungeon:enter');assert.ok(game.dungeon.complete);assert.equal(r.earnedGold(game),95);
 await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);assert.ok((await open().loadAdventure(hero)).game.dungeon.complete);
 const mage={...hero,class:'Wizard',spells:['acid-splash','missile','blur','chromatic-orb']};mage.equipment=r.equipmentFor(mage);const combat={...r.newAdventure(mage),stage:'combat'};
 assert.ok(r.dmCommand(mage,combat,'I cast Acid Splash at the wisp').action);
 assert.ok(r.dmCommand(mage,combat,'I cast Acid Splash at the wisp',{current:0,temp:0}).error);
 assert.ok(r.dmCommand(mage,{...combat,castingConditions:{silenced:true}},'I cast Acid Splash at the wisp').error);
 assert.ok(r.dmCommand(mage,{...combat,castingConditions:{handsBound:true}},'I cast Acid Splash at the wisp').error);
 assert.ok(r.dmCommand(mage,{...combat,castingConditions:{targetDistance:1000}},'I cast Acid Splash at the wisp').error);
 assert.ok(r.dmCommand(mage,{...combat,castingConditions:{clearPath:false}},'I cast Acid Splash at the wisp').error);
 assert.ok(r.dmCommand(mage,{...combat,spellSlotsUsed:[4,0,0,0,0,0,0,0,0]},'I cast Magic Missile at the wisp').error);
 assert.equal(r.dmCommand(mage,combat,'I cast Chromatic Orb at the wisp').action.request.forceDM,true);
 assert.equal(r.dmCommand(mage,combat,'I cast Magic Missile at the innkeeper').action.request.forceDM,true);
 assert.ok(r.dmCommand(mage,{...combat,concentration:{id:'bless'}},'I cast Blur on myself').error);
 const trapGame={...game,stage:'dungeon',dungeon:{...game.dungeon,room:3,trapResolved:false,visited:[0,1,3],complete:false,gold:0}};
 const trapFall=r.adventureStep(trapGame,{current:1,temp:0},hero,'dungeon:disarm',()=>0);assert.equal(trapFall.game.stage,'defeat');assert.equal(trapFall.game.dungeon.active,false);assert.equal(trapFall.health.current,0);
 await r.saveAdventure(r.adventureSnapshot(hero,trapFall.game,trapFall.health,true),hero);
 const fightGame={...trapGame,stage:'combat',enemyHP:14,dungeon:{...trapGame.dungeon,room:6,cleared:[],visited:[0,1,3,4,5,6]}};
 const fled=r.adventureStep(fightGame,{current:5,temp:0},hero,'flee',()=>0);assert.equal(fled.game.stage,'escaped');assert.equal(fled.game.dungeon.active,false);
 await r.saveAdventure(r.adventureSnapshot(hero,fled.game,fled.health,true),hero);
 console.log('Passed: eight-room dungeon, both guardians, trap, seal, one-use recovery, save/reload, completion, reward replay protection; spell conditions, range, blocked path, slots, unknown targets and costly materials.');
})().catch(e=>{console.error(e);process.exitCode=1;});
