const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let raw=null,fail=false;
const AsyncStorage={getItem:async()=>raw,setItem:async(k,v)=>{if(fail)throw Error('Disk failure');raw=v;}};
const source='const catalog='+fs.readFileSync('spellCatalog.json','utf8')+';const progression='+fs.readFileSync('spellProgression.json','utf8')+';\n'+['subclassOptions.js','campaignRules.js','mapRules.js','journalRules.js','spellOptions.js','equipmentRules.js','characterRules.js','combatRules.js','weaponRules.js','masteryRules.js','healthRules.js','spellRules.js','classActions.js','dungeonRules.js','deathRules.js','npcRules.js','relationshipRules.js','hostileEncounter.js','encounterRules.js','inventoryRules.js','adventureRules.js','partyRules.js','skillRules.js','storyRules.js','followerRules.js','adventureStorage.js','deedRules.js'].map(f=>fs.readFileSync(f,'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')).join('\n');
const open=()=>vm.runInNewContext(source+'\n({newAdventure,adventureStep,journalForGame,addJournalNote,validJournal,adventureSnapshot,saveAdventure,loadAdventure,equipmentFor})',{AsyncStorage});
(async()=>{
 const r=open(),hero={name:'Journal tester',class:'Wizard',level:1,scores:{Strength:12,Dexterity:14,Constitution:14,Intelligence:16,Wisdom:12,Charisma:10},spells:['grease']};hero.equipment=r.equipmentFor(hero);
 let game=r.newAdventure(hero),health=null;
 const act=(action,rand=()=>0)=>{const result=r.adventureStep(game,health,hero,action,rand);assert.equal(result.error,undefined);game=result.game;health=result.health;return result;};
 assert.equal(game.journal.entries.length,1);
 act('listen');act('approach');assert.equal(game.journal.entries.length,3);
 const request={id:'grease',slot:1,intent:'Make the bridge slippery.',componentsConfirmed:true};
 act({type:'spell',request});assert.equal(game.journal.entries.length,3);
 const pending=game;await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);
 game=(await open().loadAdventure(hero)).game;assert.equal(game.pendingSpell.id,'grease');
 const ruling={note:'The wisp is unaffected. The floor is slick.',damage:0,healing:0,temporaryHP:0};
 act({type:'spell-ruling',ruling});assert.equal(game.journal.entries.filter(e=>e.kind==='ruling').length,1);
 assert.ok(game.journal.entries.some(e=>e.text.includes(request.intent)&&e.text.includes(ruling.note)));
 const duplicate=r.adventureStep(game,health,hero,{type:'spell-ruling',ruling});assert.ok(duplicate.error);assert.equal(duplicate.game,game);
 for(let i=0;i<50;i++)act('dodge');assert.equal(game.log.length,40);assert.ok(game.journal.entries.some(e=>e.title==='Restore the bridge light'));
 act('flee');assert.equal(game.journal.entries.slice(-1)[0].kind,'outcome');
 game=r.addJournalNote(game,'Remember the keeper’s promise.');const original=game;
 assert.equal(r.addJournalNote(game,'   '),game);assert.equal(r.addJournalNote(game,'x'.repeat(2001)),game);
 await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);const saved=raw;
 fail=true;await assert.rejects(r.saveAdventure(r.adventureSnapshot(hero,r.addJournalNote(game,'Later'),health,true),hero));assert.equal(raw,saved);
 fail=false;await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);
 const reload=await open().loadAdventure(hero);assert.equal(JSON.stringify(reload.game.journal),JSON.stringify(game.journal));
 assert.equal(await r.loadAdventure({...hero,name:'Other hero'}),null);
 game=r.newAdventure(hero,game);assert.equal(game.journal.chapter,2);assert.ok(game.journal.entries.some(e=>e.kind==='note'));assert.equal(original.journal.chapter,1);
 const count=game.journal.entries.length;health=null;act('long-rest');assert.equal(game.journal.chapter,2);assert.equal(game.journal.entries.length,count+1);
 const legacy={stage:'victory',enemyHP:0,potions:0,round:2,log:[]};assert.ok(r.journalForGame(legacy).entries[0].text.includes('restored'));assert.equal(legacy.journal,undefined);
 const invalid={...game,journal:{...game.journal,entries:[...game.journal.entries,game.journal.entries[0]]}};
 await assert.rejects(r.saveAdventure(r.adventureSnapshot(hero,invalid,health,true),hero));
 const snap=r.adventureSnapshot(hero,game,health,true);snap.game={...game,journal:{...game.journal,nextId:0}};raw=JSON.stringify(snap);await assert.rejects(r.loadAdventure(hero));
 console.log('Passed: journal milestones, pending/confirmed rulings, duplicate prevention, >40 turns, notes, save/reload/retry, replay/rest, legacy checkpoint and corrupt-save protection.');
})().catch(e=>{console.error(e);process.exitCode=1;});
