const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let raw=null,fail=false;
const AsyncStorage={getItem:async()=>raw,setItem:async(k,v)=>{if(fail)throw Error('Disk failure');raw=v;}};
const source='const catalog='+fs.readFileSync('spellCatalog.json','utf8')+';const progression='+fs.readFileSync('spellProgression.json','utf8')+';\n'+['subclassOptions.js','campaignRules.js','mapRules.js','journalRules.js','spellOptions.js','equipmentRules.js','characterRules.js','combatRules.js','weaponRules.js','healthRules.js','spellRules.js','classActions.js','dungeonRules.js','npcRules.js','adventureRules.js','skillRules.js','storyRules.js','followerRules.js','adventureStorage.js'].map(f=>fs.readFileSync(f,'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')).join('\n');
const open=()=>vm.runInNewContext(source+'\n({travelTo,mapRoute,mapCoordinates,newAdventure,adventureStep,journalForGame,addJournalNote,validJournal,adventureSnapshot,saveAdventure,loadAdventure,equipmentFor})',{AsyncStorage});
(async()=>{
 const r=open(),hero={name:'Map tester',class:'Fighter',level:1,scores:{Strength:16,Dexterity:14,Constitution:14,Intelligence:12,Wisdom:12,Charisma:10}};hero.equipment=r.equipmentFor(hero);
 assert.equal(r.mapRoute('inn','bridge').feet,900);assert.equal(r.mapRoute('bridge','tower').minutes,4);assert.equal(r.mapRoute('inn','tower').feet,1500);assert.equal(r.mapRoute('tower','inn').minutes,5);
 const timed=r.travelTo({...r.newAdventure(hero),concentration:{id:'shield-of-faith',remaining:100,duration:'10 minutes'},temporarySpell:{id:'false-life',remaining:40}},{current:12,temp:5},'tower');assert.equal(timed.game.map.minutes,5);assert.equal(timed.game.concentration.remaining,50);assert.equal(timed.game.temporarySpell,undefined);assert.equal(timed.health.temp,0);
 let game=r.newAdventure(hero),health=null;
 const act=action=>{const result=r.adventureStep(game,health,hero,action,()=>0);assert.equal(result.error,undefined);game=result.game;health=result.health;};
 assert.ok(r.adventureStep(game,health,hero,{type:'travel',destination:'tower'}).error);
 act('listen');act({type:'travel',destination:'tower'});
 assert.equal(game.stage,'tower');assert.equal(game.map.minutes,7);assert.ok(game.map.visited.includes('tower'));
 await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);game=(await open().loadAdventure(hero)).game;
 assert.equal(game.stage,'tower');act('inspect-tower');assert.equal(game.map.clue,true);
 assert.ok(r.adventureStep(game,health,hero,'inspect-tower').error);
 act({type:'travel',destination:'inn'});act('long-rest');assert.equal(game.map.clue,true);assert.equal(game.map.accepted,true);
 assert.ok(r.adventureStep(game,health,hero,'study').error);
 game={...game,concentration:{id:'blur',remaining:10,duration:'1 minute',automaticProtection:true}};
 act({type:'travel',destination:'bridge'});assert.equal(game.concentration,undefined);
 act('call-wisp');assert.equal(game.stage,'victory');assert.equal(game.enemyHP,0);assert.equal(game.map.peaceful,true);
 assert.ok(game.journal.entries.some(e=>e.title==='A peaceful resolution'));
 assert.ok(r.adventureStep(game,health,hero,'call-wisp').error);
 await r.saveAdventure(r.adventureSnapshot(hero,game,health,true),hero);assert.equal((await open().loadAdventure(hero)).game.map.peaceful,true);
 const bad={...game,map:{...game.map,visited:['inn','bridge']}};await assert.rejects(r.saveAdventure(r.adventureSnapshot(hero,bad,health,true),hero));
 game=r.newAdventure(hero,game);assert.equal(game.map.clue,false);assert.ok(game.journal.entries.some(e=>e.title==='A peaceful resolution'));
 act('listen');assert.ok(r.adventureStep(game,health,hero,'call-wisp').error);act('approach');
 assert.ok(r.adventureStep(game,health,hero,{type:'travel',destination:'inn'}).error);
 game={...game,pendingSpell:{id:'grease',slot:1,intent:'Test target',componentsConfirmed:true}};
 assert.ok(r.adventureStep(game,health,hero,{type:'travel',destination:'tower'}).error);
 console.log('Passed: map routes, unlocks, travel timing, save/reload, unique clue, rest preservation, peaceful victory, replay, combat/pending guards and invalid save rejection.');
})().catch(e=>{console.error(e);process.exitCode=1;});
